In [2]:
import os
import pandas as pd
import numpy as np
import warnings

In [ ]:
from pathlib import Path
base_dir = Path.cwd()
file_path = os.path.join(base_dir, "DATA", "Tips.csv")

print(file_path)
# sep='/t' is used as the csv file is seperated with a tab spacing

In [6]:
data_tips = pd.read_csv(file_path)
data_tips.head()

   SINO  TotalBill  Tips Smoker  Day    Time  Size  Gender
0     1      16.99  1.01     No  Sun  Dinner   2.0  Female
1     2      10.34  1.66     No  Sun  Dinner   3.0    Male
2     3      21.01  3.50     No  Sun  Dinner   3.0    Male
3     4      23.68  3.31     No  Sun  Dinner   2.0    Male
4     5      24.59  3.61     No  Sun  Dinner   4.0  Female

In [14]:
correlation_coefficient = data_tips['TotalBill'].corr(data_tips['Tips'])
print(correlation_coefficient)

0.7647163847649967

In [11]:
print(np.ptp(data_tips['TotalBill']))
range_total_bill = np.max(data_tips['TotalBill']) - np.min(data_tips['TotalBill'])
print(range_total_bill)

nan
45.2

In [17]:
#find how many missing values(NAN) are there in 'Smoker' column 
print(data_tips['Smoker'].isna().sum())

7

In [18]:
data_tips['TotalBill'].describe()

count    98.000000
mean     19.805408
std       7.950817
min       3.070000
25%      15.017500
50%      18.285000
75%      23.965000
max      48.270000
Name: TotalBill, dtype: float64

In [21]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
'year': [2000, 2001, 2002, 2001, 2002, 2003],
'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
tryframe = pd.read_table(file_path)
tryframe.head()

  SINO,TotalBill,Tips,Smoker,Day,Time,Size,Gender
0             1,16.99,1.01,No,Sun,Dinner,2,Female
1               2,10.34,1.66,No,Sun,Dinner,3,Male
2                3,21.01,3.5,No,Sun,Dinner,3,Male
3               4,23.68,3.31,No,Sun,Dinner,2,Male
4             5,24.59,3.61,No,Sun,Dinner,4,Female

In [26]:
data_tips.columns.values
print(list(data_tips.columns.values))
print(data_tips.columns)
for col in data_tips.columns:
  print(col)

['SINO', 'TotalBill', 'Tips', 'Smoker', 'Day', 'Time', 'Size', 'Gender']
Index(['SINO', 'TotalBill', 'Tips', 'Smoker', 'Day', 'Time', 'Size', 'Gender'], dtype='object')
SINO
TotalBill
Tips
Smoker
Day
Time
Size
Gender